### ISSUE TITLE
esc should clear ship selection

### ISSUE THREAD

**Issue by bleakley** [bleakley/starfarer#5]

**Comment by max-radin** [comment]
I'd vote for eliminating esc as a control, and just use tab and w and get out of weapon and target selections.

**Comment by bleakley** [comment]
You don't think pressing tab repeatedly should cycle you back to your first target?

**Comment by max-radin** [comment]
My inclination is that if you press it enough it deselects everything...one less key for users to have to figure out. 

Also I was thinking though it might be cool at some point to have something where merely targeting another ship (without firing) could make them hostile...they can tell you have weapons locked on them.

**Comment by bleakley** [comment]
Hmm that is interesting, I think it would be too easy to inadvertently do that though.
